

from enum import StrEnum


class PreflightStatus(StrEnum):
    PASSED = "passed"
    FAILED = "failed"


LIFECYCLE_PHASE_PREFLIGHT = "preflight"

NAV_ASSERT_POSITION_IN_GEOMETRY = "NAV_ASSERT_POSITION_IN_GEOMETRY"
NAV_ASSERT_ARRIVAL_IN_GEOMETRY = "NAV_ASSERT_ARRIVAL_IN_GEOMETRY"
NAV_ASSERT_DEPARTURE_TIME = "NAV_ASSERT_DEPARTURE_TIME"
NAV_ASSERT_FLIGHT_BAND = "NAV_ASSERT_FLIGHT_BAND"

